name: checks

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: npm

      - name: Install Node dependencies
        run: npm ci

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy, rustfmt
          rustflags: ""

      - name: Check Rust
        run: npm run check:rust

      - name: Run tests
        run: npm test
